---
- name: Run LVM snapshot readiness check before create
  ansible.builtin.include_tasks: check.yml

- name: Execute LVM snapshot create
  ansible.builtin.include_role:
    name: infra.lvm_snapshots.snapshot_create
  vars:
    snapshot_create_volumes: "{{ lvm_snapshot_eligible_volumes }}"
  when:
    - lvm_snapshot_eligible_volumes | length > 0