---
- name: Validate AWS snapshot action
  assert:
    that:
      - snapshot_action is defined
      - snapshot_action in ['check', 'create', 'remove', 'revert']
    fail_msg: "snapshot_action must be one of: check, create, remove, revert"

- name: Run AWS snapshot check
  include_tasks: check.yml
  when:
    - snapshot_action == "check"

- name: Run AWS snapshot create
  include_tasks: create.yml
  when:
    - snapshot_action == "create"

- name: Run AWS snapshot remove
  include_tasks: remove.yml
  when:
    - snapshot_action == "remove"

- name: Run AWS snapshot revert
  include_tasks: revert.yml
  when:
    - snapshot_action == "revert"