---
- name: Run LVM snapshot readiness check before revert
  ansible.builtin.include_tasks: check.yml

- name: Execute LVM snapshot revert
  ansible.builtin.include_role:
    name: infra.lvm_snapshots.snapshot_revert
  vars:
    snapshot_revert_volumes: "{{ lvm_snapshot_eligible_volumes }}"
  when:
    - lvm_snapshot_eligible_volumes | length > 0