---
galaxy_info:
  author: philip860
  description: AWS EBS snapshot provider role for philip860.leapp_snapshot
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags:
    - leapp
    - rhel
    - snapshot
    - aws
    - ec2
    - ebs

dependencies: []